### ISSUE TITLE
Vita not updating database after Memory Swap

### ISSUE THREAD

**Issue by cutecryptid** [theKlanc/VitaMemorySwap#2]
I don't know where this issue comes from (if it's a Vita thing or a MemorySwap thing) so if it's a Vita thing, close this issue, please.

Lately I've been having issues with the tool because even if it swaps plugins correctly (as checked on vitashell) the console doesn't rebuild the database as it should after swapping, therefore making the old icons of the LiveArea stay and not adding the new ones from the other card.

Is there a way to tell the Vita to rebuild the DB after swapping?

**Comment by theKlanc** [comment]
You can rebuild the database manually by entering recovery mode following these steps:

•Ensure that the Vita console is turned off 
•Press the PS button, Power button and Right Shoulder Button at the same time and hold for couple of seconds.

Still, it seems kinda strange, the only thing this does is swap two files, so it shouldn't be related to that. Try creating a file at ux0: and then swapping, then open vitashell again and check if it is at uma0:, if it's not, then it didn't swap correctly. Keep me informed on this if you can.

**Comment by cutecryptid** [comment]
I've checked that the mount points for both memcard and sd2vita swap correctly, in fact, if I try to run any app that is on the swapped storage (for example, being on memcard, swapping and then tryin to run an app that is stored on memcard) it gives an error. 

If I rebuild the database manually with Vitashell, new icons get added but old ones remain. But if I rebuild it through recovery, it works fine, but it's a bit of a hassle and of course, the LiveArea layout goes back to default.

I'm gonna try unlinking the memory card on the Vita (+Henkaku ofc) settings and then see if that affects somehow to the rebuild after swap thing. I'll reply in a while after I try.

**Comment by cutecryptid** [comment]
Somehow, after unlinking my memcard (While having the Memcard mounted as ux0:) made it work again. I don't know if it's 100% safe that this is a valid workaround but if this happens to other users of the tool, it might be useful for them to try...
